### ISSUE TITLE
open_path doesn't work

### ISSUE THREAD

**Issue by savetheclocktower** [barkerest/hidapi#1]
Forgive me for filing a bug against a project that's a few weeks old, but I stumbled across this and I think it's perfect for a thing I'm working on.

When I try...

``` ruby
HIDAPI::open_path("/dev/hidapi/ipac@1-1.3")
```
I get...

```
NoMethodError: undefined method `make_path` for HIDAPI:Module
```
…because `make_path` isn't yet implemented in either `HIDAPI` or `HIDAPI::Engine`. I'd fix this myself if I had the relevant expertise, but I'm already way out of my comfort zone.

Thanks for writing this!

**Comment by barkerest** [comment]
Thanks for pointing that out.  If we're going to go to the trouble to have udev give us a friendly path, we might as well be able to use it.  On Linux, you can now open /dev/hidapi/* paths.  I also fixed the call to HIDAPI::make_path() since that should have been HIDAPI::Device::make_path().

The patched module has been pushed to Rubygems as hidapi version 0.1.5.
Let me know if this resolves your issue.

**Comment by savetheclocktower** [comment]
Awesome. I figured it was also possible I was using the method wrong, and that this was more of a feature request than a bug report. :) I'll try this out when I'm able. Thanks!
